stages:
  - build
  - deploy

services:
  - docker:dind

image: docker:20

before_script:
  - apk add --no-cache shellcheck w3m curl jq gawk grep bash
  - find . -name "*.sh" -maxdepth 1 -print0 | xargs -0 -r -n1 bash -n
  - find . -name "*.sh" -maxdepth 1 -print0 | xargs -0 -r -n1 shellcheck
  - export CURRENT_ALPINE_VERSION="$(w3m -dump https://alpinelinux.org/releases/ | grep "edge" -A1 | tail -1 | awk '{print $1}' | cut -d "v" -f 2)"
  - export OPENSSH_VERSION="$(w3m -dump "https://pkgs.alpinelinux.org/packages?name=openssh&branch=v${CURRENT_ALPINE_VERSION}" | grep -m 1 "x86" | awk '{print $2}')"
  - echo "Building Open-SSH in version '${OPENSSH_VERSION}' on Alpine '${CURRENT_ALPINE_VERSION}'"

build:docker:
  stage: build
  script:
    - >
      docker build
      --no-cache
      --pull
      --build-arg ALPINE_VERSION="${CURRENT_ALPINE_VERSION}"
      --build-arg OPENSSH_VERSION="${OPENSSH_VERSION}"
      --tag "${IMAGE_NAME}:${OPENSSH_VERSION}-alpine${ALPINE_VERSION}"
      --tag "${IMAGE_NAME}:${OPENSSH_VERSION}-alpine"
      --tag "${IMAGE_NAME}:${OPENSSH_VERSION}"
      --tag "${IMAGE_NAME}:latest"
      --file "${CI_PROJECT_DIR}/Dockerfile"
      "${CI_PROJECT_DIR}"
  except:
    - master
  parallel:
    matrix:
      - IMAGE_NAME: [ "hermsi/alpine-sshd" ]

deploy:docker:
  stage: deploy
  script:
    - >
      docker build
      --no-cache
      --pull
      --build-arg ALPINE_VERSION="${CURRENT_ALPINE_VERSION}"
      --build-arg OPENSSH_VERSION="${OPENSSH_VERSION}"
      --tag "${IMAGE_NAME}:${OPENSSH_VERSION}-alpine${CURRENT_ALPINE_VERSION}"
      --tag "${IMAGE_NAME}:${OPENSSH_VERSION}-alpine"
      --tag "${IMAGE_NAME}:${OPENSSH_VERSION}"
      --tag "${IMAGE_NAME}:latest"
      --file "${CI_PROJECT_DIR}/Dockerfile"
      "${CI_PROJECT_DIR}"
    - >
      mkdir -p "${HOME}/.docker" &&
      mv "${DOCKER_CONFIG_JSON}" "${HOME}/.docker/config.json" &&
      chmod 0600 "${HOME}/.docker/config.json"
    - docker push "${IMAGE_NAME}:${OPENSSH_VERSION}-alpine${CURRENT_ALPINE_VERSION}"
    - docker push "${IMAGE_NAME}:${OPENSSH_VERSION}-alpine"
    - docker push "${IMAGE_NAME}:${OPENSSH_VERSION}"
    - docker push "${IMAGE_NAME}:latest"
  only:
    - master
  parallel:
    matrix:
      - IMAGE_NAME: [ "hermsi/alpine-sshd", "quay.io/hermsi1337/alpine-sshd" ]
      - IMAGE_NAME: [ "hermsi/alpine-sshd", "quay.io/hermsi1337/alpine-sshd" ]